# Generated by Django 3.2.15 on 2026-03-18 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Note title', help_text='Give a short title to the note', max_length=100, verbose_name='Title')),
                ('text', models.TextField(help_text='Add details', verbose_name='Text')),
                ('slug', models.SlugField(blank=True, help_text='Provide a slug for the note page. Use only Latin letters, numbers, hyphens and underscores', max_length=100, unique=True, verbose_name='Slug for the note page')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
